### ISSUE TITLE
Force UTC dates

### ISSUE THREAD

**Issue by JoeKlimcak** [hoangnm/react-native-week-view#163]
Can one force UTC dates? I know we can set locales, but (correct me if I'm wrong) there's no UTC locale. 

The idea is that all users see the same UTC time, whatever their locale. Currently it seems like default timezones are being used, so even though I'm passing an object with a UTC date time, it shifts the boxes in the weekview according to my timezone.

**Comment by pdpino** [comment]
You are correct, there is no UTC locale. Locales are for languages, while UTC is a timezone.

Working with timezones is still a bit rough in this library, since the `WeekView` component always shows the dates with the _timezone in the user's phone_.

I have had a similar issue, my current workaround (without any additional library) is to manually create a date with the UTC values before passing it to `events`:
```js
  const date = new Date(2022, 2, 1, 15) // any date in your timezone
  const utcDate = new Date(
    date.getUTCFullYear(),
    date.getUTCMonth(),
    date.getUTCDate(),
    date.getUTCHours(),
    date.getUTCMinutes(),
    date.getUTCSeconds(),
    date.getUTCMilliseconds(),
  );
  return utcDate;
```

In the future we could support timezones, suggestions are welcomed :rocket:

**Comment by JoeKlimcak** [comment]
That works, thank you @pdpino!
