### ISSUE TITLE
It is not responsive to orientation change.

### ISSUE THREAD

**Issue by DarshanAjudiya** [hoangnm/react-native-week-view#38]
when i transform from portrait to landscape or vice versa  mode it does not change width of the block.

**Comment by hoangnm** [comment]
The library does not support this feature at the moment. Are you using for tablet?

**Comment by DarshanAjudiya** [comment]
no, I'm using a mobile device.
another thing is can you add support of dynamic width as corresponding to its parent component.

**Comment by tomussss** [comment]
The problem is located within the package styles' height and width variables, i.e. it uses Dimensions.get('screen') to get the current width/height, which is not responsive to orientation change (though the values do change after the rotation is complete). 

For now what is create function to detect the max/min dimensions of the screen and use them instead of just screen/window width: 
`import {Dimensions} from 'react-native';


const getMinDimension = () => {
    const { height, width } = Dimensions.get('screen');
    const min = Math.min(height, width);
    return min;
}

const getMaxDimension = () => {
    const { height, width } = Dimensions.get('screen');
    const max = Math.max(height, width);
    return max;
}

export {getMinDimension, getMaxDimension}`

Instead of `const { width: SCREEN_WIDTH } = Dimensions.get('window');` i use `getMaxDimensions()` (I set it to the maximum because i only need the landscape version).
This allows me to get the current dimensions and apply them to style the components. Also this could be improoved by adding a listener on the orientation change to dynamically change the values. Might be a bit hacky, but works for me 

Hope this helps!
