### ISSUE TITLE
description unreadable with short duration events

### ISSUE THREAD

**Issue by yanir401** [hoangnm/react-native-week-view#50]
![image](https://user-images.githubusercontent.com/65459107/94931672-b3babb00-04d0-11eb-9f0d-48ba3ac50f97.png)
Any recommendations for a workaround?

Thanks

**Comment by yanir401** [comment]
Hi there, I managed to find a solution with the hoursInDisplay, but now I have a new issue when I'm booking events in sequence. see the image:
![image](https://user-images.githubusercontent.com/65459107/94935674-00ed5b80-04d6-11eb-8fe6-d8afb1665d93.png)


also, do you have a way to limit the hours inside the view (based on the range of hours of fetched data)


Thanks

**Comment by pdpino** [comment]
> Any recommendations for a workaround?

Don't know if is the best idea, but you could use the `EventComponent` prop, and pass a custom react component that includes a text and adjust the size:
```js
const MyComponent = ({ event, position }) => (
  <Text style={{ padding: 5, fontSize: calculateFontSize(position.height) }}>
    {event.description}
  </Text>
)
```
In `calculateFontSize()` you would customize the font size given the height of the event: if the event is too small, you could make the `fontSize` smaller. You can customize the text further, such as displaying only a shortened description, etc.
See an example for the usage of this prop [in the readme]((you can see [the commit](https://github.com/pdpino/react-native-week-view/commit/df74a1dd3702cd4714f4fb1f61a7b8deff7b6edd))).

---

>  I have a new issue when I'm booking events in sequence.

This is because the events are overlapped, i.e. the second event starts at the same time or before the first event ends.
I had a similar problem and applied a hacky solution: added an `allowOverlapSeconds` prop, which indicates the amount of seconds the events can be overlapped without displaying them smaller in width. For example, if your events are overlapped by 1 second, using `allowOverlapSeconds = 1` would fix this.
@hoangnm I can send a PR with this change if is not too hacky, you can see [the commit here](https://github.com/pdpino/react-native-week-view/commit/df74a1dd3702cd4714f4fb1f61a7b8deff7b6edd)

---

> do you have a way to limit the hours inside the view (based on the range of hours of fetched data)

This is the purpose of the `hoursInDisplay` prop, to indicate the amount of hours showing (e.g. if `hoursInDisplay == 12`, the component should show from 8am to 8pm). I think the amount is currently miscalculated, and the hours actually displayed are less (e.g. if you set `hoursInDisplay = 12`, it may show only 10 or 11 hours). We could try and fix this.

**Comment by pdpino** [comment]
>  I have a new issue when I'm booking events in sequence.

This is because the events are overlapped, i.e. the second event starts at the same time or before the first event ends.
I had a similar problem and applied a hacky solution: added an `allowOverlapSeconds` prop, which indicates the amount of seconds the events can be overlapped without displaying them smaller in width. For example, if your events are overlapped by 1 second, using `allowOverlapSeconds = 1` would fix this.
@hoangnm I can send a PR with this change if is not too hacky, you can see [the commit here](https://github.com/pdpino/react-native-week-view/commit/df74a1dd3702cd4714f4fb1f61a7b8deff7b6edd)

**Comment by pdpino** [comment]
> do you have a way to limit the hours inside the view (based on the range of hours of fetched data)

This is the purpose of the `hoursInDisplay` prop, to indicate the amount of hours showing (e.g. if `hoursInDisplay == 12`, the component should show from 8am to 8pm). I think the amount is currently miscalculated, and the hours actually displayed are less (e.g. if you set `hoursInDisplay = 12`, it may show only 10 or 11 hours). We could try and fix this bug.

**Comment by hoangnm** [comment]
@pdpino about the events in sequence issue, I agree that the width of event items should be full width of the column. But can we just have a constant for it?

**Comment by pdpino** [comment]
@hoangnm do you mean not passing as prop? something like `ALLOW_OVERLAP_SECONDS = 2`?
Sure, I can do that

**Comment by pdpino** [comment]
@yanir401 were u able to apply a workaround for your use case? The latest PR #53 should fix the overlap problem

**Comment by RimApp** [comment]
Nice, I encountered the same problem, when will the changes be integrated on the master ?

**Comment by pdpino** [comment]
@RimApp which problem of the described here? the (1) description unreadable with short events or (2) events in sequence overlapping?

For (1), you should be able to apply any of the fixes [described in the comment above](https://github.com/hoangnm/react-native-week-view/issues/50#issuecomment-702816068). If that does not work for you, please let me know.

For (2), the **changes are already merged to master** (PR #53). Events that are overlapped by less than 2 seconds should not get shrinked in width. Again, if you have any issues with this let me know :slightly_smiling_face:

**Comment by flobady** [comment]
it works perfectly on the master branch. would you consider publishing a release with all these changes? the last release was end of September.
Thank!

**Comment by RimApp** [comment]
My bad, it's work perfectly :)

**Comment by pdpino** [comment]
@hoangnm I think u can close this issue?

**Comment by hoangnm** [comment]
yes, thanks for your help @pdpino !
