### ISSUE TITLE
Is it possible to change the height of each time slot?

### ISSUE THREAD

**Issue by jeminsieow** [hoangnm/react-native-week-view#91]
Is it possible to change the height of the time grid? I want to be able to squeeze more timings in the screen.

Something like this:

![image](https://user-images.githubusercontent.com/26967037/117649720-70d96800-b1c2-11eb-820f-ab58c060cf8a.png)

Loving the library, thanks in advance!

**Comment by pdpino** [comment]
I think we can improve this and give more control to the user. I propose the following:

* Add a `timeStep` _(Number)_ prop, which would allow the user setting the step used in the time labels. Examples:
    * if set to `timeStep={60} // minutes`, the labels will be 12:00, 13:00, 14:00 and so on.
    * if set to `timeStep={30} // minutes`, the labels will be 12:00, 12:30, 13:00 and so on.
* Hence, by changing the props `timeStep` and `hoursInDisplay`, you can control the slot height and the amount of time fitting in the screen at the same time.

@jeminsieow would this work better for you?
@hoangnm any thoughts?

(we can use other prop name if preferred)

**Comment by jeminsieow** [comment]
@pdpino I think adding the timeStep would be the perfect solution.

**Comment by pdpino** [comment]
Ok, I will try to implement this, hopefully this week!

**Comment by hoangnm** [comment]
Thanks, @pdpino, it's a good idea to have the `timeStep` prop. However, by having to use two props, it may be hard to understand for anyone trying to set the height of the time slot. I'm thinking that if we can let a user set the height they want instead.

**Comment by pdpino** [comment]
That's true. I think that problem comes from the `hoursInDisplay` prop, rather than `timeStep`. For example, think of a prop `slotHeight`, if an user sets `slotHeight={30}` (in pixels), the `hoursInDisplay` prop would not be needed, but still the component needs to know how many minutes to use as step (a time-step), e.g. 30 minutes, 1 hour, etc. In other words `slotHeight` is independent from `timeStep`, but redundant with `hoursInDisplay`.

So, **I think we should add `timeStep` to allow the user setting that value, and decide what to do with `hoursInDisplay` and a possible `slotHeight` prop.** Options:

1. Use both `hoursInDisplay` and `slotHeight`. If the user provides a `slotHeight` value in pixels, this value is used to set the height. If not provided, fallback to `hoursInDisplay`, which calculates `slotHeight = SCREEN_HEIGHT / hoursInDisplay` (or something like that).
    * Advantages:
      * Backward compatible
      * Flexible: allows the user setting pixels directly (`slotHeight`), or a value depending on screen-size (`hoursInDisplay`)
    * Disadvantages:
      * It may be hard to understand the use of 3 props
      * We would have 2 redundant props, which may get ugly in the `WeekView` code
2. Use only `slotHeight`, and delete `hoursInDisplay`.
    * Advantages:
      * Is easy to understand for the user: set the amount of pixels directly.
    * Disadvantages:
      * Not backward compatible (a prop is deleted)
      * The number of pixels is hardcoded, which may look different in different screens.
3. Use only `hoursInDisplay`
    * Advantages:
      * Backward compatible
    * Disadvantages:
      * The user cannot set height in pixels directly. The user can only decide the amount of hours to show in the screen.

I prefer option 1, although I acknowledge is not ideal (it still has disadvantages).

@hoangnm what do you think? Does this make sense?

**Comment by pdpino** [comment]
I created a PR adding the `timeStep` prop.

@jeminsieow with this, you should be able to increase `hoursInDisplay`, keep `timeStep={60}` (the default value) and be able to squeeze more time-labels in the screen, as your example.

@hoangnm I think we could add this prop to give more control to the users, and figure out what to do with `hoursInDisplay` and `slotHeight` later.

**Comment by jeminsieow** [comment]
@pdpino Looks good! When can it be merged?

**Comment by hoangnm** [comment]
> I created a PR adding the `timeStep` prop.
> 
> @jeminsieow with this, you should be able to increase `hoursInDisplay` and keep `timeStep={60}` (the default value) to squeeze more time-labels in the screen, as your example.
> 
> @hoangnm I suggest we add this prop now to give more control to the users, and figure out what to do with the `hoursInDisplay` and `slotHeight` props later.

Agreed, @pdpino , @jeminsieow . I just merged the PR.
